name: Manual Release

# This workflow will be triggered manually using workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag for the release'
        required: true
      release_title:
        description: 'Release title'
        required: true
      release_body:
        description: 'Release description or notes'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.ghrelease }}
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_body }}
          draft: false
          prerelease: false

      - name: Output release URL
        run: echo "Release created at ${{ steps.create_release.outputs.html_url }}"